@echo off
mkdir msvc64
mkdir msvc32
cmake -H. -Bmsvc64  -G "Visual Studio 14 2015 Win64" -DBUILD_BENCHMARKS=FALSE -DBUILD_STATIC=TRUE -DBUILD_WITH_RTTI=FALSE -DBUILD_WITH_STATIC_RUNTIME_LIBS=FALSE
cmake -H. -Bmsvc32  -G "Visual Studio 14 2015" -DBUILD_BENCHMARKS=FALSE -DBUILD_STATIC=TRUE -DBUILD_WITH_RTTI=FALSE -DBUILD_WITH_STATIC_RUNTIME_LIBS=FALSE
